In [1]:
import pandas as pd

In [2]:
import numpy as np

In [3]:
data_preprocessed=pd.read_csv('Absenteeism_preprocessed.csv')

In [4]:
data_preprocessed.head()

Reason_1  Reason_2  Reason_3  Reason_4  Month Value  Day of the Week  \
0         0         0         0         1            7                1   
1         0         0         0         0            7                1   
2         0         0         0         1            7                2   
3         1         0         0         0            7                3   
4         0         0         0         1            7                3   

   Transportation Expense  Distance to Work  Age  Daily Work Load Average  \
0                     289                36   33                  239.554   
1                     118                13   50                  239.554   
2                     179                51   38                  239.554   
3                     279                 5   39                  239.554   
4                     289                36   33                  239.554   

   Body Mass Index  Education  Children  Pets  Absenteeism Time in Hours  
0               30          0         2     1                          4  
1               31          0         1     0                          0  
2               31          0         0     0                          2  
3               24          0         2     0                          4  
4               30          0         2     1                          2

In [5]:
data_preprocessed['Absenteeism Time in Hours'].median()

3.0

In [6]:
targets = np.where(data_preprocessed['Absenteeism Time in Hours'] >data_preprocessed['Absenteeism Time in Hours'].median(),1,0)

In [7]:
targets

array([1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0,
       1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1,
       0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1,
       0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1,
       0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0,
       1, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1,
       0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1,
       1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1,
       0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0,
       0, 0, 0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 1, 0, 0,
       0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0,

In [8]:
data_preprocessed['Excessive Absenteeism']=targets

In [9]:
data_preprocessed.head()

Reason_1  Reason_2  Reason_3  Reason_4  Month Value  Day of the Week  \
0         0         0         0         1            7                1   
1         0         0         0         0            7                1   
2         0         0         0         1            7                2   
3         1         0         0         0            7                3   
4         0         0         0         1            7                3   

   Transportation Expense  Distance to Work  Age  Daily Work Load Average  \
0                     289                36   33                  239.554   
1                     118                13   50                  239.554   
2                     179                51   38                  239.554   
3                     279                 5   39                  239.554   
4                     289                36   33                  239.554   

   Body Mass Index  Education  Children  Pets  Absenteeism Time in Hours  \
0               30          0         2     1                          4   
1               31          0         1     0                          0   
2               31          0         0     0                          2   
3               24          0         2     0                          4   
4               30          0         2     1                          2   

   Excessive Absenteeism  
0                      1  
1                      0  
2                      0  
3                      1  
4                      0

In [10]:
targets.sum()/targets.shape[0]

0.45571428571428574

In [11]:
data_with_targets=data_preprocessed.drop(['Absenteeism Time in Hours'],axis=1)

In [12]:
data_with_targets is data_preprocessed

False

In [13]:
data_with_targets.shape

(700, 15)

In [14]:
data_with_targets.iloc[:,:-1]

Reason_1  Reason_2  Reason_3  Reason_4  Month Value  Day of the Week  \
0           0         0         0         1            7                1   
1           0         0         0         0            7                1   
2           0         0         0         1            7                2   
3           1         0         0         0            7                3   
4           0         0         0         1            7                3   
..        ...       ...       ...       ...          ...              ...   
695         1         0         0         0            5                2   
696         1         0         0         0            5                2   
697         1         0         0         0            5                3   
698         0         0         0         1            5                3   
699         0         0         0         1            5                3   

     Transportation Expense  Distance to Work  Age  Daily Work Load Average  \
0                       289                36   33                  239.554   
1                       118                13   50                  239.554   
2                       179                51   38                  239.554   
3                       279                 5   39                  239.554   
4                       289                36   33                  239.554   
..                      ...               ...  ...                      ...   
695                     179                22   40                  237.656   
696                     225                26   28                  237.656   
697                     330                16   28                  237.656   
698                     235                16   32                  237.656   
699                     291                31   40                  237.656   

     Body Mass Index  Education  Children  Pets  
0                 30          0         2     1  
1                 31          0         1     0  
2                 31          0         0     0  
3                 24          0         2     0  
4                 30          0         2     1  
..               ...        ...       ...   ...  
695               22          1         2     0  
696               24          0         1     2  
697               25          1         0     0  
698               25          1         0     0  
699               25          0         1     1  

[700 rows x 14 columns]

In [15]:
unscaled_inputs=data_with_targets.iloc[:,:-1]

In [16]:
#from sklearn.preprocessing import StandardScaler
#absenteeism_scaler=StandardScaler()

In [56]:
from sklearn.base import BaseEstimator, TransformerMixin
from sklearn.preprocessing import StandardScaler

class CustomScaler(BaseEstimator,TransformerMixin): 
    
    def __init__(self,columns,copy=True,with_mean=True,with_std=True):
        self.scaler = StandardScaler(copy,with_mean,with_std)
        self.columns = columns
        self.mean_ = None
        self.var_ = None

    def fit(self, X, y=None):
        self.scaler.fit(X[self.columns], y)
        self.mean_ = np.mean(X[self.columns])
        self.var_ = np.var(X[self.columns])
        return self

    def transform(self, X, y=None, copy=None):
        init_col_order = X.columns
        X_scaled = pd.DataFrame(self.scaler.transform(X[self.columns]), columns=self.columns)
        X_not_scaled = X.loc[:,~X.columns.isin(self.columns)]
        return pd.concat([X_not_scaled, X_scaled], axis=1)[init_col_order]

In [57]:
unscaled_inputs.columns.values

array(['Reason_1', 'Reason_2', 'Reason_3', 'Reason_4', 'Month Value',
       'Day of the Week', 'Transportation Expense', 'Distance to Work',
       'Age', 'Daily Work Load Average', 'Body Mass Index', 'Education',
       'Children', 'Pets'], dtype=object)

In [86]:
#columns_to_scale=['Month Value','Day of the Week', 'Transportation Expense', 'Distance to Work',
       #'Age', 'Daily Work Load Average', 'Body Mass Index', 'Education','Children', 'Pets']
columns_to_omit = ['Reason_1', 'Reason_2', 'Reason_3', 'Reason_4','Education']

In [87]:
columns_to_scale = [x for x in unscaled_inputs.columns.values if x not in columns_to_omit]

In [88]:
absenteeism_scaler=CustomScaler(columns_to_scale)

In [89]:
absenteeism_scaler.fit(unscaled_inputs)

CustomScaler(columns=['Month Value', 'Day of the Week',
                      'Transportation Expense', 'Distance to Work', 'Age',
                      'Daily Work Load Average', 'Body Mass Index', 'Children',
                      'Pets'],
             copy=None, with_mean=None, with_std=None)

In [90]:
scaled_inputs=absenteeism_scaler.transform(unscaled_inputs)

In [91]:
scaled_inputs

Reason_1  Reason_2  Reason_3  Reason_4  Month Value  Day of the Week  \
0           0         0         0         1     0.182726        -0.683704   
1           0         0         0         0     0.182726        -0.683704   
2           0         0         0         1     0.182726        -0.007725   
3           1         0         0         0     0.182726         0.668253   
4           0         0         0         1     0.182726         0.668253   
..        ...       ...       ...       ...          ...              ...   
695         1         0         0         0    -0.388293        -0.007725   
696         1         0         0         0    -0.388293        -0.007725   
697         1         0         0         0    -0.388293         0.668253   
698         0         0         0         1    -0.388293         0.668253   
699         0         0         0         1    -0.388293         0.668253   

     Transportation Expense  Distance to Work       Age  \
0                  1.005844          0.412816 -0.536062   
1                 -1.574681         -1.141882  2.130803   
2                 -0.654143          1.426749  0.248310   
3                  0.854936         -1.682647  0.405184   
4                  1.005844          0.412816 -0.536062   
..                      ...               ...       ...   
695               -0.654143         -0.533522  0.562059   
696                0.040034         -0.263140 -1.320435   
697                1.624567         -0.939096 -1.320435   
698                0.190942         -0.939096 -0.692937   
699                1.036026          0.074838  0.562059   

     Daily Work Load Average  Body Mass Index  Education  Children      Pets  
0                  -0.806331         0.767431          0  0.880469  0.268487  
1                  -0.806331         1.002633          0 -0.019280 -0.589690  
2                  -0.806331         1.002633          0 -0.919030 -0.589690  
3                  -0.806331        -0.643782          0  0.880469 -0.589690  
4                  -0.806331         0.767431          0  0.880469  0.268487  
..                       ...              ...        ...       ...       ...  
695                -0.853789        -1.114186          1  0.880469 -0.589690  
696                -0.853789        -0.643782          0 -0.019280  1.126663  
697                -0.853789        -0.408580          1 -0.919030 -0.589690  
698                -0.853789        -0.408580          1 -0.919030 -0.589690  
699                -0.853789        -0.408580          0 -0.019280  0.268487  

[700 rows x 14 columns]

In [92]:
scaled_inputs.shape

(700, 14)

In [93]:
from sklearn.model_selection import train_test_split

In [94]:
train_test_split(scaled_inputs,targets)

[     Reason_1  Reason_2  Reason_3  Reason_4  Month Value  Day of the Week  \
 331         1         0         0         0     1.324766         1.344231   
 306         0         0         0         1     1.039256         0.668253   
 310         1         0         0         0     1.039256        -0.007725   
 444         0         0         0         1    -0.102784         0.668253   
 209         1         0         0         0    -0.388293        -0.007725   
 ..        ...       ...       ...       ...          ...              ...   
 409         0         0         0         1    -0.959313         1.344231   
 67          0         0         0         1     1.039256         1.344231   
 115         0         0         0         1    -1.530333        -0.683704   
 343         0         0         0         1     1.610276        -0.683704   
 651         1         0         0         0    -0.959313        -1.359682   
 
      Transportation Expense  Distance to Work       Age  \
 3

In [95]:
x_train,x_test,y_train,y_test=train_test_split(scaled_inputs,targets, train_size=0.8, random_state=20)

In [96]:
print(x_train.shape,y_train.shape)

(560, 14) (560,)


In [97]:
print(x_test.shape,y_test.shape)

(140, 14) (140,)


In [98]:
from sklearn.linear_model import LogisticRegression
from sklearn import metrics

In [99]:
reg = LogisticRegression()

In [100]:
reg.fit(x_train,y_train)

C:\Users\Aula\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)


LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='warn', n_jobs=None, penalty='l2',
                   random_state=None, solver='warn', tol=0.0001, verbose=0,
                   warm_start=False)

In [101]:
reg.score(x_train,y_train)

0.7714285714285715

In [102]:
model_outputs= reg.predict(x_train)
model_outputs

array([0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0,
       0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 1, 1, 1,
       1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0,
       0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 1, 0,
       0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0,
       0, 1, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0,
       1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0,
       0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1,
       1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1,
       1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1,
       0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1,
       0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0,
       0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0,

In [103]:
y_train

array([0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0,
       1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1,
       1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0,
       0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 1,
       1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0,
       0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1,
       0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0,
       0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1,
       1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0,
       1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0,
       0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0,
       1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0,

In [104]:
model_outputs == y_train

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True, False,  True, False, False,  True,  True,  True,  True,
       False,  True, False,  True, False, False,  True,  True,  True,
       False,  True,  True,  True,  True,  True,  True,  True,  True,
       False, False, False, False,  True, False,  True,  True,  True,
        True,  True,  True,  True,  True, False,  True,  True,  True,
        True,  True,  True,  True,  True, False,  True,  True,  True,
        True,  True,  True,  True, False,  True, False,  True,  True,
        True,  True,  True, False,  True,  True,  True,  True,  True,
       False,  True, False,  True,  True, False, False, False,  True,
        True,  True,  True,  True,  True,  True,  True, False,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True, False,  True,  True,  True,  True,
       False,  True,  True,  True,  True, False,  True,  True,  True,
        True,  True,

In [105]:
np.sum((model_outputs == y_train))

432

In [106]:
model_outputs.shape[0]

560

In [107]:
np.sum((model_outputs == y_train))/model_outputs.shape[0]

0.7714285714285715

In [108]:
reg.intercept_

array([-1.47082548])

In [109]:
reg.coef_

array([[ 2.62614283,  0.84432   ,  2.93971875,  0.67771914,  0.16145652,
        -0.08257256,  0.60695978, -0.00741802, -0.16862442, -0.00383568,
         0.26749958, -0.23085763,  0.35572764, -0.28559431]])

In [110]:
feature_name = unscaled_inputs.columns.values

In [111]:
summary_table = pd.DataFrame (columns=['Feature name'],data=feature_name)
summary_table['Coefficient']=np.transpose(reg.coef_)
summary_table

Feature name  Coefficient
0                  Reason_1     2.626143
1                  Reason_2     0.844320
2                  Reason_3     2.939719
3                  Reason_4     0.677719
4               Month Value     0.161457
5           Day of the Week    -0.082573
6    Transportation Expense     0.606960
7          Distance to Work    -0.007418
8                       Age    -0.168624
9   Daily Work Load Average    -0.003836
10          Body Mass Index     0.267500
11                Education    -0.230858
12                 Children     0.355728
13                     Pets    -0.285594

In [112]:
summary_table.index=summary_table.index + 1
summary_table.loc[0]=['Intercept',reg.intercept_[0]]
summary_table=summary_table.sort_index()
summary_table

Feature name  Coefficient
0                 Intercept    -1.470825
1                  Reason_1     2.626143
2                  Reason_2     0.844320
3                  Reason_3     2.939719
4                  Reason_4     0.677719
5               Month Value     0.161457
6           Day of the Week    -0.082573
7    Transportation Expense     0.606960
8          Distance to Work    -0.007418
9                       Age    -0.168624
10  Daily Work Load Average    -0.003836
11          Body Mass Index     0.267500
12                Education    -0.230858
13                 Children     0.355728
14                     Pets    -0.285594

In [113]:
summary_table['Odds_ratio']=np.exp(summary_table.Coefficient)

In [114]:
summary_table

Feature name  Coefficient  Odds_ratio
0                 Intercept    -1.470825    0.229736
1                  Reason_1     2.626143   13.820360
2                  Reason_2     0.844320    2.326395
3                  Reason_3     2.939719   18.910527
4                  Reason_4     0.677719    1.969381
5               Month Value     0.161457    1.175221
6           Day of the Week    -0.082573    0.920745
7    Transportation Expense     0.606960    1.834845
8          Distance to Work    -0.007418    0.992609
9                       Age    -0.168624    0.844826
10  Daily Work Load Average    -0.003836    0.996172
11          Body Mass Index     0.267500    1.306693
12                Education    -0.230858    0.793852
13                 Children     0.355728    1.427219
14                     Pets    -0.285594    0.751567

In [115]:
summary_table.sort_values('Odds_ratio',ascending=False)

Feature name  Coefficient  Odds_ratio
3                  Reason_3     2.939719   18.910527
1                  Reason_1     2.626143   13.820360
2                  Reason_2     0.844320    2.326395
4                  Reason_4     0.677719    1.969381
7    Transportation Expense     0.606960    1.834845
13                 Children     0.355728    1.427219
11          Body Mass Index     0.267500    1.306693
5               Month Value     0.161457    1.175221
10  Daily Work Load Average    -0.003836    0.996172
8          Distance to Work    -0.007418    0.992609
6           Day of the Week    -0.082573    0.920745
9                       Age    -0.168624    0.844826
12                Education    -0.230858    0.793852
14                     Pets    -0.285594    0.751567
0                 Intercept    -1.470825    0.229736

In [ ]:
#Testing the model

In [119]:
reg.score(x_test,y_test)

0.7428571428571429

In [120]:
predicted_proba = reg.predict_proba(x_test)
predicted_proba

array([[0.73685721, 0.26314279],
       [0.60918629, 0.39081371],
       [0.41367898, 0.58632102],
       [0.80123548, 0.19876452],
       [0.07360132, 0.92639868],
       [0.31482473, 0.68517527],
       [0.30996677, 0.69003323],
       [0.13143709, 0.86856291],
       [0.79426475, 0.20573525],
       [0.75019913, 0.24980087],
       [0.48367988, 0.51632012],
       [0.19799007, 0.80200993],
       [0.07753484, 0.92246516],
       [0.70995519, 0.29004481],
       [0.30224948, 0.69775052],
       [0.57267672, 0.42732328],
       [0.54083385, 0.45916615],
       [0.57389761, 0.42610239],
       [0.38014204, 0.61985796],
       [0.04814556, 0.95185444],
       [0.69716193, 0.30283807],
       [0.79219655, 0.20780345],
       [0.39173151, 0.60826849],
       [0.4186287 , 0.5813713 ],
       [0.25818169, 0.74181831],
       [0.75527615, 0.24472385],
       [0.51057945, 0.48942055],
       [0.86794852, 0.13205148],
       [0.19785515, 0.80214485],
       [0.78285796, 0.21714204],
       [0.

In [121]:
predicted_proba.shape

(140, 2)

In [122]:
predicted_proba[:,1]

array([0.26314279, 0.39081371, 0.58632102, 0.19876452, 0.92639868,
       0.68517527, 0.69003323, 0.86856291, 0.20573525, 0.24980087,
       0.51632012, 0.80200993, 0.92246516, 0.29004481, 0.69775052,
       0.42732328, 0.45916615, 0.42610239, 0.61985796, 0.95185444,
       0.30283807, 0.20780345, 0.60826849, 0.5813713 , 0.74181831,
       0.24472385, 0.48942055, 0.13205148, 0.80214485, 0.21714204,
       0.3749067 , 0.68956837, 0.68976236, 0.53913229, 0.20780345,
       0.50790295, 0.21408487, 0.75084196, 0.43502114, 0.58927018,
       0.22777885, 0.43722182, 0.21924622, 0.43428676, 0.81295852,
       0.58244563, 0.69724136, 0.27338655, 0.20552251, 0.18317411,
       0.59131998, 0.38115576, 0.67045219, 0.28704924, 0.8497776 ,
       0.46817998, 0.89190316, 0.25870233, 0.35673457, 0.35514834,
       0.72095696, 0.6618861 , 0.31310986, 0.79285261, 0.20025819,
       0.26743725, 0.09841081, 0.2328088 , 0.73526565, 0.32952965,
       0.2134669 , 0.32994943, 0.90821459, 0.43626886, 0.61791

In [123]:
##Save model

In [124]:
import pickle

In [125]:
with open('model','wb') as file:
    pickle.dump(reg,file)

In [126]:
with open('scaler','wb') as file:
    pickle.dump(absenteeism_scaler,file)